import 'package:flutter/material.dart';

class TestScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text(
        'hi',
      ),
    );
  }
}

List list2 = [
  {
    "list": [
      {
        "_returnType": "json",
        "coGrade": "",
        "coValue": "-",
        "dataTerm": "",
        "dataTime": "2020-04-23 17:00",
        "khaiGrade": "",
        "khaiValue": "-",
        "mangName": "도로변대기",
        "no2Grade": "",
        "no2Value": "-",
        "numOfRows": "10",
        "o3Grade": "",
        "o3Value": "-",
        "pageNo": "1",
        "pm10Grade": "",
        "pm10Grade1h": "",
        "pm10Value": "-",
        "pm10Value24": "-",
        "pm25Grade": "",
        "pm25Grade1h": "",
        "pm25Value": "-",
        "pm25Value24": "-",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "",
        "so2Value": "-",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "",
        "coValue": "-",
        "dataTerm": "",
        "dataTime": "2020-04-23 16:00",
        "khaiGrade": "",
        "khaiValue": "-",
        "mangName": "도로변대기",
        "no2Grade": "",
        "no2Value": "-",
        "numOfRows": "10",
        "o3Grade": "",
        "o3Value": "-",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "",
        "pm10Value": "-",
        "pm10Value24": "50",
        "pm25Grade": "1",
        "pm25Grade1h": "",
        "pm25Value": "-",
        "pm25Value24": "14",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "",
        "so2Value": "-",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "1",
        "coValue": "0.3",
        "dataTerm": "",
        "dataTime": "2020-04-23 15:00",
        "khaiGrade": "2",
        "khaiValue": "69",
        "mangName": "도로변대기",
        "no2Grade": "1",
        "no2Value": "0.012",
        "numOfRows": "10",
        "o3Grade": "2",
        "o3Value": "0.045",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "2",
        "pm10Value": "54",
        "pm10Value24": "49",
        "pm25Grade": "1",
        "pm25Grade1h": "1",
        "pm25Value": "14",
        "pm25Value24": "13",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "1",
        "so2Value": "0.003",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "1",
        "coValue": "0.3",
        "dataTerm": "",
        "dataTime": "2020-04-23 14:00",
        "khaiGrade": "2",
        "khaiValue": "68",
        "mangName": "도로변대기",
        "no2Grade": "1",
        "no2Value": "0.011",
        "numOfRows": "10",
        "o3Grade": "2",
        "o3Value": "0.047",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "2",
        "pm10Value": "55",
        "pm10Value24": "48",
        "pm25Grade": "1",
        "pm25Grade1h": "1",
        "pm25Value": "12",
        "pm25Value24": "14",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "1",
        "so2Value": "0.003",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "1",
        "coValue": "0.3",
        "dataTerm": "",
        "dataTime": "2020-04-23 13:00",
        "khaiGrade": "2",
        "khaiValue": "67",
        "mangName": "도로변대기",
        "no2Grade": "1",
        "no2Value": "0.008",
        "numOfRows": "10",
        "o3Grade": "2",
        "o3Value": "0.044",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "2",
        "pm10Value": "57",
        "pm10Value24": "47",
        "pm25Grade": "1",
        "pm25Grade1h": "1",
        "pm25Value": "12",
        "pm25Value24": "14",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "1",
        "so2Value": "0.003",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "1",
        "coValue": "0.3",
        "dataTerm": "",
        "dataTime": "2020-04-23 12:00",
        "khaiGrade": "2",
        "khaiValue": "65",
        "mangName": "도로변대기",
        "no2Grade": "1",
        "no2Value": "0.009",
        "numOfRows": "10",
        "o3Grade": "2",
        "o3Value": "0.042",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "2",
        "pm10Value": "49",
        "pm10Value24": "45",
        "pm25Grade": "1",
        "pm25Grade1h": "1",
        "pm25Value": "11",
        "pm25Value24": "14",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "1",
        "so2Value": "0.003",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "1",
        "coValue": "0.4",
        "dataTerm": "",
        "dataTime": "2020-04-23 11:00",
        "khaiGrade": "2",
        "khaiValue": "64",
        "mangName": "도로변대기",
        "no2Grade": "1",
        "no2Value": "0.012",
        "numOfRows": "10",
        "o3Grade": "2",
        "o3Value": "0.036",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "2",
        "pm10Value": "53",
        "pm10Value24": "44",
        "pm25Grade": "1",
        "pm25Grade1h": "1",
        "pm25Value": "15",
        "pm25Value24": "15",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "1",
        "so2Value": "0.004",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "1",
        "coValue": "0.4",
        "dataTerm": "",
        "dataTime": "2020-04-23 10:00",
        "khaiGrade": "2",
        "khaiValue": "62",
        "mangName": "도로변대기",
        "no2Grade": "1",
        "no2Value": "0.014",
        "numOfRows": "10",
        "o3Grade": "2",
        "o3Value": "0.032",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "2",
        "pm10Value": "47",
        "pm10Value24": "42",
        "pm25Grade": "1",
        "pm25Grade1h": "1",
        "pm25Value": "14",
        "pm25Value24": "15",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "1",
        "so2Value": "0.004",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "1",
        "coValue": "0.4",
        "dataTerm": "",
        "dataTime": "2020-04-23 09:00",
        "khaiGrade": "2",
        "khaiValue": "59",
        "mangName": "도로변대기",
        "no2Grade": "1",
        "no2Value": "0.014",
        "numOfRows": "10",
        "o3Grade": "1",
        "o3Value": "0.028",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "2",
        "pm10Value": "42",
        "pm10Value24": "39",
        "pm25Grade": "1",
        "pm25Grade1h": "1",
        "pm25Value": "14",
        "pm25Value24": "15",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "1",
        "so2Value": "0.004",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      },
      {
        "_returnType": "json",
        "coGrade": "1",
        "coValue": "0.4",
        "dataTerm": "",
        "dataTime": "2020-04-23 08:00",
        "khaiGrade": "2",
        "khaiValue": "57",
        "mangName": "도로변대기",
        "no2Grade": "1",
        "no2Value": "0.022",
        "numOfRows": "10",
        "o3Grade": "1",
        "o3Value": "0.018",
        "pageNo": "1",
        "pm10Grade": "2",
        "pm10Grade1h": "2",
        "pm10Value": "35",
        "pm10Value24": "37",
        "pm25Grade": "1",
        "pm25Grade1h": "2",
        "pm25Value": "18",
        "pm25Value24": "15",
        "resultCode": "",
        "resultMsg": "",
        "rnum": 0,
        "serviceKey": "",
        "sidoName": "",
        "so2Grade": "1",
        "so2Value": "0.004",
        "stationCode": "",
        "stationName": "",
        "totalCount": "",
        "ver": ""
      }
    ],
    "parm": {
      "_returnType": "json",
      "coGrade": "",
      "coValue": "",
      "dataTerm": "DAILY",
      "dataTime": "",
      "khaiGrade": "",
      "khaiValue": "",
      "mangName": "",
      "no2Grade": "",
      "no2Value": "",
      "numOfRows": "10",
      "o3Grade": "",
      "o3Value": "",
      "pageNo": "1",
      "pm10Grade": "",
      "pm10Grade1h": "",
      "pm10Value": "",
      "pm10Value24": "",
      "pm25Grade": "",
      "pm25Grade1h": "",
      "pm25Value": "",
      "pm25Value24": "",
      "resultCode": "",
      "resultMsg": "",
      "rnum": 0,
      "serviceKey":
          "tQuWrySn7Slv2VuEru+/zsHhKaW9Cdo82oMxjA2rMSA8osCpN/mcfQzoBYySkni+mEQniFf/lwjlU4JVGm9iMA==",
      "sidoName": "",
      "so2Grade": "",
      "so2Value": "",
      "stationCode": "",
      "stationName": "시흥대로",
      "totalCount": "",
      "ver": "1.3"
    },
    "ArpltnInforInqireSvcVo": {
      "_returnType": "json",
      "coGrade": "",
      "coValue": "",
      "dataTerm": "DAILY",
      "dataTime": "",
      "khaiGrade": "",
      "khaiValue": "",
      "mangName": "",
      "no2Grade": "",
      "no2Value": "",
      "numOfRows": "10",
      "o3Grade": "",
      "o3Value": "",
      "pageNo": "1",
      "pm10Grade": "",
      "pm10Grade1h": "",
      "pm10Value": "",
      "pm10Value24": "",
      "pm25Grade": "",
      "pm25Grade1h": "",
      "pm25Value": "",
      "pm25Value24": "",
      "resultCode": "",
      "resultMsg": "",
      "rnum": 0,
      "serviceKey":
          "tQuWrySn7Slv2VuEru+/zsHhKaW9Cdo82oMxjA2rMSA8osCpN/mcfQzoBYySkni+mEQniFf/lwjlU4JVGm9iMA==",
      "sidoName": "",
      "so2Grade": "",
      "so2Value": "",
      "stationCode": "",
      "stationName": "시흥대로",
      "totalCount": "",
      "ver": "1.3"
    },
    "totalCount": 23
  }
];

List<Object> list = [
  {
    "response": {
      "header": {"resultCode": "00", "resultMsg": "NORMAL_SERVICE"},
      "body": {
        "dataType": "JSON",
        "items": {
          "item": [
            {
              "baseDate": "20200427",
              "baseTime": "1200",
              "category": "PTY",
              "nx": 58,
              "ny": 125,
              "obsrValue": "0"
            },
            {
              "baseDate": "20200427",
              "baseTime": "1200",
              "category": "REH",
              "nx": 58,
              "ny": 125,
              "obsrValue": "29"
            },
            {
              "baseDate": "20200427",
              "baseTime": "1200",
              "category": "RN1",
              "nx": 58,
              "ny": 125,
              "obsrValue": "0"
            },
            {
              "baseDate": "20200427",
              "baseTime": "1200",
              "category": "T1H",
              "nx": 58,
              "ny": 125,
              "obsrValue": "16.6"
            },
            {
              "baseDate": "20200427",
              "baseTime": "1200",
              "category": "UUU",
              "nx": 58,
              "ny": 125,
              "obsrValue": "0.6"
            },
            {
              "baseDate": "20200427",
              "baseTime": "1200",
              "category": "VEC",
              "nx": 58,
              "ny": 125,
              "obsrValue": "344"
            },
            {
              "baseDate": "20200427",
              "baseTime": "1200",
              "category": "VVV",
              "nx": 58,
              "ny": 125,
              "obsrValue": "-2"
            },
            {
              "baseDate": "20200427",
              "baseTime": "1200",
              "category": "WSD",
              "nx": 58,
              "ny": 125,
              "obsrValue": "2.2"
            }
          ]
        },
        "pageNo": 1,
        "numOfRows": 10,
        "totalCount": 8
      }
    }
  }
];
